### ISSUE TITLE
Java error when trying to forwardGeocode

### ISSUE THREAD

**Issue by fzamperin** [sebastianbaar/cordova-plugin-nativegeocoder#55]
**Describe the bug**
After updating to 3.3.0 using the forwardGeocode function, it gives me the error: ```Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.toString()' object reference ```, this is happening on Android, iOS works fine. I downgraded to 3.2.2 and is working flawless again for Android.

**To Reproduce**
I just updated to the new version and then the problem started.

**Expected behavior**
To not give me the error and return Latitude/Longitude.

**Plugin Version**
v3.3.0

**Smartphone (please complete the following information):**
 - Device: Xiaomi Pocophone F1
 - OS: Android 10

**Additional context**
On iOS is working great, when I downgrade to version 3.2.2 it works on Android.

**Comment by sebastianbaar** [comment]
Hi @fzamperin,
I do not own a Xiaomi Pocophone F1 but I tested on Android 10 and cannot reproduce your error. Could you please give me some more infos?! Do you have a call stack for this error? Which method are you calling to reproduce your error (e.g.: both for forward and reverse geocoding)?
I would really like to help you, but I need more infos!

Cheers

**Comment by fzamperin** [comment]
I`ve installed the plugin again with the new version in order to test it, this bug happens with the forwardGeocode function, this is the stack trace from Logcat:

```
2020-03-27 09:24:15.075 26914-27292/br.com.eatsforyou E/PluginManager: Uncaught exception from plugin
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.toString()' on a null object reference
        at cordova.plugin.nativegeocoder.NativeGeocoder.forwardGeocode(NativeGeocoder.java:118)
        at cordova.plugin.nativegeocoder.NativeGeocoder.execute(NativeGeocoder.java:53)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:181)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

I'm using ionic-native in order to call the plugin: v4.15.0, the string I'm passing to the plugin is: ```991 Rua Maestro Elias Lobo Jardim Paulista São Paulo São Paulo 01433-000 ```, even though any string does not work for me, if there's something more I can do, let me know.

**Comment by sebastianbaar** [comment]
Hey @fzamperin,
yes it's a bug. Thank you for the stack trace. I will fix this. Meanwhile you can fix the error on your side by adding `options` to the forwardGeocode function:

```
const OPTIONS: NativeGeocoderOptions = {
  useLocale: true,
  maxResults: 1
};
this.nativeGeocoder.forwardGeocode('991 Rua Maestro ...', OPTIONS)  <-- HERE
```

`options` cannot be null. That's a bug I am going to fix.
